### ISSUE TITLE
Entidade de Relacionamento

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor#10]
O Modelo ER e o Esquema Relacional  representam como os dados (conceitos ou entidades) importantes da aplicação se relacionam e podem ser mapeados para tabelas implementadas no banco de dados relacional.

**Comment by Maia2098** [comment]
@Ana-MP , conforme falamos fazer o último ajuste na entidade de relacionamento nos moldes do diagrama do @TiagoAraujo12 .

**Comment by Ana-MP** [comment]
Boa Noite, enviei as modificações e a ferramenta que estou usando é Visual Paradigm
