### ISSUE TITLE
Diagrama de Fluxo

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor#11]
Aspectos de usabilidade são modelados no Diagrama de Fluxo (fluxograma) para representar as interações entre os usuários e o sistema, e aplicá-las no Wireframe interativo.  Deverão ser observadas normas de qualidade de software, principalmente em relação a funcionalidade, usabilidade e padrões de codificação.

**Comment by ChristianeCuri** [comment]
Diagrama de fluxo criado numa primeira versão e inserido no Projeto de Interface para validação pelo grupo.

**Comment by Maia2098** [comment]
Fazer a alteração para que o usuário tenha acesso as receitas antes de estar logado.

Login apenas para compartilhar, avaliar e comentar as receitas.

**Comment by ChristianeCuri** [comment]
Feito. Inserida a versão 2 do diagrama de fluxo.

**Comment by Maia2098** [comment]
@ChrisCuri , fiz um comentário no issue dos planos, depois consegue ver?

Acho que podemos conversar sobre!

**Comment by Maia2098** [comment]
@ChrisCuri , adicionar no fluxo a funcionalidade de compartilhar receita (link). RF-009: Permitir que o usuário compatilhe as receitas nas redes sociais.

Adicionar, após login do usuário, a possibilidade dele favoritar receita - RF-006 - Permitir que o usuário adicione mídias referentes a receita (Foto e vídeos).

**Comment by Maia2098** [comment]
Apta para homologação.
