### ISSUE TITLE
Diagrama de classe

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor#13]

**Comment by Maia2098** [comment]
@TiagoAraujo12 , conforme falamos, seguiremos com a elaboração do Diagrama de Classes com Usuário e Receita.

**Comment by TiagoAraujo12** [comment]
Diagrama inserido.

[DiagramaDeClasseInspiraSabor.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor/files/14795804/DiagramaDeClasseInspiraSabor.pdf)

![image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor/assets/125419720/39e12bbb-a6a5-4b70-8ecd-03894a8df7f1)

**Comment by TiagoAraujo12** [comment]
Alterando diagrama para inclusão do titulo da receita

![image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor/assets/125419720/c9ac718c-1f69-4327-8c1b-91226c479d13)
