### ISSUE TITLE
Esquema Relacional

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor#14]
Nessa etapa você também deverá elaborar também o Modelo ER e Esquema Relacional. O Modelo ER e o Esquema Relacional  representam como os dados (conceitos ou entidades) importantes da aplicação se relacionam e podem ser mapeados para tabelas implementadas no banco de dados relacional.

**Comment by TiagoAraujo12** [comment]
@Maia2098, 

Inclusão do esquema Relacional

![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor/assets/125419720/c759a6c0-3768-4d95-ba13-d02de120903c)
