### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor#15]
Em relação ao Projeto de Interface, deverá ser definido a visão geral da interação do usuário pelas telas do sistema e protótipo interativo das telas com as funcionalidades que fazem parte do sistema (wireframes).

**Comment by Maia2098** [comment]
Alinhamos em colocar que as receitas aparecem sem, obrigatoriamente, a necessidade de login, ver receitas.

O login vai ser só compartilhar receitas, avaliar, comentar.

**Comment by g413rie1** [comment]
Wireframe criado, fico aguardando feedback do grupo para eventual modificação.

**Comment by Maia2098** [comment]
O professor gostou do wireframe criado conforme reunião de quinta.

**Comment by Maia2098** [comment]
@Jonathan-Rocha e @g413rie1 , conforme falamos, vamos tentar um pequeno esboço de front.
