### ISSUE TITLE
Elaboração de Requisitos

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor#3]
@Jonathan-Rocha , prosseguir conforme nós conversamos.

Gentileza lembrar que a definição de requisitos é fundamental para que o @g413rie1 , o @TiagoAraujo12 e a @Ana-MP possam prosseguir com os trabalhos deles.

**Comment by Jonathan-Rocha** [comment]
Adicionei os RF, RNF e as restrições do projeto conforme o combinado.

Obs.:
- O requisito não funcional RNF-005 marquei com (?) porque não achei referencia de como vamos fazer a hospedagem do APP.  E se de fato precisa ser feito, pois se trata de um app mobile que é baixado e usado meio que nativamente.
- O requisito não funcional RNF-003 também marquei com (?) porque eu vi no material de apoio das etapas de desenvolvimento, materias sobre o banco de dados SQLite. Provavelmente vamos usar ele nos microfundamentos.

Podemos confirmar esses dois pontos com o professor nas reunião quinta.

**Comment by Maia2098** [comment]
@Jonathan-Rocha , acabei de verificar os requisitos, acho que todos estão de acordo com nossa reunião.

Acredito que podemos revisitar a prioridade deles.

Talvez o RF-009 (compartilha receitas) terá uma prioridade maior.

No mais, estou de acordo com todos.

RNF-005 E 003 validaremos quinta.

**Comment by Maia2098** [comment]
Validado.
