### ISSUE TITLE
Diagrama de Casos de Uso

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor#4]
@TiagoAraujo12 prosseguir com a elaboração do Diagrama.

Você se baseará nos requisitos delimitados pelo @Jonathan-Rocha e que estarão criados até amanhã.

**Comment by TiagoAraujo12** [comment]
Caso de uso criado com base nos requisitos funcionais



![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor/assets/125419720/3a0c444f-5d58-43da-88fa-fbc6d7348f44)



[DiagramaUso.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor/files/14517233/DiagramaUso.pdf)

**Comment by TiagoAraujo12** [comment]
Alterando a imagem do caso de uso.

[DiagramaUso.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor/files/14551591/DiagramaUso.pdf)
![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor/assets/125419720/2b40dab3-70c4-472f-9b82-458359765dea)

**Comment by Maia2098** [comment]
Validado.
