### ISSUE TITLE
Personas e História de Usuários

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor#5]
@Ana-MP , como você já vem desempenhando essa função nos últimos semestres, definimos que você será a elaborada das personas e histórias de usuários.

Entendemos que, para o nosso objetivo, precisamos de 3 perfis. São eles:

1) Uma pessoa que não possui muita habilidade com aplicativos;

2) Uma pessoa que quer compartilhar receitas com seus amigos;

3) Uma pessoa que quer achar receitas fáceis.

Baseie-se nos requisitos que serão elaborados pelo @Jonathan-Rocha . O prazo dele é amanhã à noite.

**Comment by Maia2098** [comment]
@Ana-MP , público-alvo inserido:

Este projeto é voltado para todas as pessoas que são novatas na cozinha e até mesmo para aquelas pessoas que se consideram entusiastas da culinária. Esses usuários prezam pela praticidade do aplicativo que forneça de forma simples e direta as receitas que desejam cozinhar. Podem ser adultos de todas as idades e backgrounds no uso de aplicativos móveis.

**Comment by Ana-MP** [comment]
Eu criei cinco personas e suas histórias de usuários correspondentes. Amanhã, vamos revisar com o professor para garantir se essa quantidade é adequada ou se precisamos ajustar alguma coisa

**Comment by Maia2098** [comment]
Validar - se vamos criar mais uma persona
"Preguiçoso"

**Comment by Ana-MP** [comment]
Incluído mais uma persona

**Comment by Maia2098** [comment]
Validado.
