### ISSUE TITLE
Matriz de Rastreabilidade

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor#6]
@g413rie1 prosseguir após a elaboração dos requisitos pelo @Jonathan-Rocha .

Lembre-se de comentar por aqui.

**Comment by g413rie1** [comment]
Obrigado pelo lembrete, já estou trabalhando na documentação.

**Comment by g413rie1** [comment]
Adicionado a matriz de rastreabilidade. Verificar com o professor se há necessidade de acrescentar stakeholders e casos de uso na matriz.

**Comment by Maia2098** [comment]
A matriz vai evoluir conforme o tempo
Colocar os casos de uso.

**Comment by g413rie1** [comment]
Adicionado casos de uso como instruído pelo orientador.

**Comment by Maia2098** [comment]
Validado.
