### ISSUE TITLE
Gerenciamento de Projeto

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor#7]
@ChrisCuri , gentileza assumir essa demanda como elaboradora principal.

Conversaremos mais com o professor na quinta mas, por hora, podemos seguir conforme falamos na discussão.

Sinta-se livre para usar eventuais fluxos do canva ou, se o microfundamento der ideias melhores, podemos seguir com eles.

**Comment by ChristianeCuri** [comment]
Iniciei a construção do cronograma utilizando o programa Project Libre. O detalhamento da etapa 1 no cronograma está quase finalizado e vou inserir essa prévia na Especificação do projeto.

**Comment by ChristianeCuri** [comment]
Inserido o orçamento do projeto na especificação.

**Comment by Maia2098** [comment]
Vamos verificar com o professor se o quadro kanban pode ser colocado na gestão de equipe.

**Comment by Maia2098** [comment]
Foto:



![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor/assets/100796561/af984d72-92f2-4c51-b90b-c9d6d8591a9a)

**Comment by Maia2098** [comment]
Pode colocar o quadro.

**Comment by Maia2098** [comment]
Fazer um ajuste no orçamento.
Podemos cortar o custo de equipamento e móveis.

**Comment by ChristianeCuri** [comment]
Orçamento já ajustado. Inseri sua imagem do kanban na gestão de equipe. E atualizei a imagem do gerenciamento de tempo com todo o planejamento do projeto para o semestre.

**Comment by Maia2098** [comment]
Validado.
