### ISSUE TITLE
Metodologia 

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-inspirasabor#8]
A documentação do projeto deverá ter uma seção de Metodologia. Nessa seção serão definidas informações sobre os ambientes de trabalho utilizados pela equipe para desenvolver o projeto, além da definição do processo e das ferramentas através dos quais a equipe se organizará.

**Comment by Maia2098** [comment]
Realizada inclusão de divisão de tarefas, planejamento e ferramentas.

@g413rie1 , @Ana-MP , @TiagoAraujo12 , @ChrisCuri , @Jonathan-Rocha , me informem as ferramentas que estão utilizando para os artefatos para eu atualizar a documentação.

**Comment by ChristianeCuri** [comment]
Cronograma de atividades: ProjectLibre
Diagrama de fluxo: Lucidchart
Modelagem de processos em padrão BPMN: Bizagi Modeler
